default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: to_love_roo_2_development

test:
  <<: *default
  database: to_love_roo_2_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 20
